apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector: 
     app: mahajavaapp
  template:
    metadata:
      labels:
        app: mahajavaapp
    spec:
      containers:
      - name: mycotainer
        image: maha4iac/mymahaapp:1
        ports:
        - containerPort: 8080

             


    
