apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector: 
     app: myjavaapp
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
      - name: mycotainer
        image: maha4iac/mahaonlinestore:1
        ports:
        - containerPort: 8080