apiVersion: v1
kind: Servive
metadata:
  name: maha-svc
  labels: 
    app: myjavaapp
spec:
  type: NodePort
  ports:
  - ports: 8080
    nodeport: 30001
    protocol: TCP
  selector:        
    app: myjavaapp